
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Oct 04 16:04:04 EDT 2007
//----------------------------------------------------

package edu.umass.eflux;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OFF = 32;
  public static final int TIMER = 31;
  public static final int PLATFORM = 27;
  public static final int PIPE = 8;
  public static final int SESSION = 25;
  public static final int QUESTION = 19;
  public static final int EXCLAMATION = 5;
  public static final int LEFT_PAREN = 13;
  public static final int SEMI = 12;
  public static final int RIGHT_SQ_BRACE = 16;
  public static final int STAR = 4;
  public static final int IDENTIFIER = 21;
  public static final int ERROR = 23;
  public static final int COLON = 9;
  public static final int PROGRAM = 24;
  public static final int EQUALS = 11;
  public static final int COMMA = 10;
  public static final int SOURCEDEF = 18;
  public static final int NUMBER = 20;
  public static final int EOF = 0;
  public static final int CONNECTION = 26;
  public static final int TIME = 33;
  public static final int TYPEDEF = 17;
  public static final int RIGHT_CR_BRACE = 7;
  public static final int SYNC = 29;
  public static final int error = 1;
  public static final int ARROW = 3;
  public static final int LEFT_CR_BRACE = 6;
  public static final int MAX = 30;
  public static final int RIGHT_PAREN = 14;
  public static final int LEFT_SQ_BRACE = 15;
  public static final int ATOMIC = 2;
  public static final int HANDLE = 22;
  public static final int STATEORDER = 28;
}

